<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< HEAD
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-16T17:17:18 SAST" name="Suite" finished-at="2025-07-16T17:18:09 SAST" duration-ms="51195">
=======
<testng-results retried="3" ignored="0" total="8" passed="2" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-11T11:37:06 SAST" name="Suite" finished-at="2025-07-11T11:37:28 SAST" duration-ms="21700">
>>>>>>> e1049039be4fa2ebd9bbf76e3d9804f40bd8685c
    <groups>
      <group name="Regression">
        <method signature="Reporting.generateAllReportsAndAssertStatusMessages()[pri:0, instance:UtilipayV2Hybrid.testCases.Reporting@7c351808]" name="generateAllReportsAndAssertStatusMessages" class="UtilipayV2Hybrid.testCases.Reporting"/>
      </group> <!-- Regression -->
    </groups>
<<<<<<< HEAD
    <test started-at="2025-07-16T17:17:18 SAST" name="Utilipay Version 2" finished-at="2025-07-16T17:18:09 SAST" duration-ms="51195">
      <class name="UtilipayV2Hybrid.testCases.Reporting">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:UtilipayV2Hybrid.testCases.Reporting@7c351808]" started-at="2025-07-16T17:17:18 SAST" name="setUp" finished-at="2025-07-16T17:17:25 SAST" duration-ms="6988" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setupReportingModule()[pri:0, instance:UtilipayV2Hybrid.testCases.Reporting@7c351808]" started-at="2025-07-16T17:17:25 SAST" name="setupReportingModule" finished-at="2025-07-16T17:17:28 SAST" duration-ms="2350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupReportingModule -->
        <test-method signature="generateAllReportsAndAssertStatusMessages()[pri:0, instance:UtilipayV2Hybrid.testCases.Reporting@7c351808]" started-at="2025-07-16T17:17:28 SAST" name="generateAllReportsAndAssertStatusMessages" finished-at="2025-07-16T17:18:08 SAST" duration-ms="40837" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateAllReportsAndAssertStatusMessages -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UtilipayV2Hybrid.testCases.Reporting@7c351808]" started-at="2025-07-16T17:18:08 SAST" name="tearDown" finished-at="2025-07-16T17:18:09 SAST" duration-ms="435" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- UtilipayV2Hybrid.testCases.Reporting -->
=======
    <test started-at="2025-07-11T11:37:06 SAST" name="Utilipay Version 2" finished-at="2025-07-11T11:37:28 SAST" duration-ms="21700">
      <class name="UtilipayV2Hybrid.testCases.Api">
        <test-method is-config="true" signature="authentication()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:07 SAST" name="authentication" finished-at="2025-07-11T11:37:13 SAST" duration-ms="6658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authentication -->
        <test-method signature="emsVendTest()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:13 SAST" name="emsVendTest" finished-at="2025-07-11T11:37:27 SAST" duration-ms="13045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emsVendTest -->
        <test-method retried="true" signature="switchMeterLookup()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:27 SAST" name="switchMeterLookup" finished-at="2025-07-11T11:37:27 SAST" duration-ms="550" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Meter Lookup request failed expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Meter Lookup request failed expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at UtilipayV2Hybrid.testCases.Api.switchMeterLookup(Api.java:190)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchMeterLookup -->
        <test-method signature="switchMeterLookup()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:27 SAST" name="switchMeterLookup" finished-at="2025-07-11T11:37:27 SAST" duration-ms="252" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Meter Lookup request failed expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Meter Lookup request failed expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at UtilipayV2Hybrid.testCases.Api.switchMeterLookup(Api.java:190)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchMeterLookup -->
        <test-method retried="true" signature="switchMunLookup()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:27 SAST" name="switchMunLookup" finished-at="2025-07-11T11:37:27 SAST" duration-ms="128" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Municipality Lookup request failed expected [200] but found [415]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Municipality Lookup request failed expected [200] but found [415]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at UtilipayV2Hybrid.testCases.Api.switchMunLookup(Api.java:157)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchMunLookup -->
        <test-method signature="switchMunLookup()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:27 SAST" name="switchMunLookup" finished-at="2025-07-11T11:37:28 SAST" duration-ms="137" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Municipality Lookup request failed expected [200] but found [415]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Municipality Lookup request failed expected [200] but found [415]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at UtilipayV2Hybrid.testCases.Api.switchMunLookup(Api.java:157)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchMunLookup -->
        <test-method retried="true" signature="switchVend()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:28 SAST" name="switchVend" finished-at="2025-07-11T11:37:28 SAST" duration-ms="131" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Switch vend request failed expected [200] but found [415]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Switch vend request failed expected [200] but found [415]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at UtilipayV2Hybrid.testCases.Api.switchVend(Api.java:170)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchVend -->
        <test-method signature="switchVend()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:28 SAST" name="switchVend" finished-at="2025-07-11T11:37:28 SAST" duration-ms="122" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Switch vend request failed expected [200] but found [415]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Switch vend request failed expected [200] but found [415]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at UtilipayV2Hybrid.testCases.Api.switchVend(Api.java:170)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchVend -->
        <test-method signature="confirmTransactionTest()[pri:0, instance:UtilipayV2Hybrid.testCases.Api@7a7471ce]" started-at="2025-07-11T11:37:28 SAST" name="confirmTransactionTest" finished-at="2025-07-11T11:37:28 SAST" depends-on-methods="UtilipayV2Hybrid.testCases.Api.emsVendTest" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirmTransactionTest -->
      </class> <!-- UtilipayV2Hybrid.testCases.Api -->
>>>>>>> e1049039be4fa2ebd9bbf76e3d9804f40bd8685c
    </test> <!-- Utilipay Version 2 -->
  </suite> <!-- Suite -->
</testng-results>
